---
apiVersion: skaffold/v2beta29
kind: Config
requires:
# # - configs:
# #   - common
# #   - mysql
# #   - rabbitmq
# #   path: /Users/gregorybulgare/Works/devstack/
# - git: 
#     repo: git@github.com:leangeder/java-config-server.git
#     path: skaffold.yaml
#     ref: main
#     sync: true
#   activeProfiles:
#   - name: default
#     activatedBy: [dev]
- path: ../config-server/
build:
  artifacts:
  - image: harbor.platform.pe.core.underwriteme.co.uk/private/config-client
    context: .
    docker:
      dockerfile: Dockerfile
      cacheFrom:
      - "harbor.platform.pe.core.underwriteme.co.uk/private/config-client:latest"
  tagPolicy:
    sha256: {}
  local:
    useDockerCLI: true
    push: false
deploy:
  kustomize:
    paths:
    - .k8s/base/
profiles:
- name: dev
  activation:
  - command: dev
  patches:
  - op: replace
    path: /deploy/kustomize/paths/0
    value: .k8s/dev/
  portForward:
  - resourceType: service
    resourceName: config-client
    port: 8080
