---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  environment: "dev"
  team: "teams-a"
  spring-profile: "customer_a_dev"
resources:
- ../base/
replicas:
- name: config-client
  count: 1
